name: Online Journalism
favicon: null
layout_spectrum: 0.7869716074783355
typography_spectrum: 0.24903
title: 'Subhash Rai: An Indian Online Journalist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#324a3a'
    - '#4e705f'
    - '#658776'
    - '#83b1ae'
    - '#92c987'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.4299063354264945
purpose: []
